### ISSUE TITLE
Line plots should have markers

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mslice#105]
The 1D plots should always display point markers as described by http://matplotlib.org/api/axes_api.html#matplotlib.axes.Axes.plot

@mducle What would be an acceptable default?

**Comment by mducle** [comment]
@martyngigg `'bo'` (blue circles) is typically the default (in `Matlab` at least) - and I think this would fine for us to have.

**Comment by mducle** [comment]
Resolved by #134
