### ISSUE TITLE
Remember cut `param` values for different directions 

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mslice#106]
This basically means storing previous parameters for cuts along `E` and `Q` separately.

**Comment by mducle** [comment]
I've got a rough implementation in the `demo3` branch - specifically these two commits: https://github.com/mantidproject/mslice/commit/9796602d3f1f671a36b8dc04235f29827fd7768e and https://github.com/mantidproject/mslice/commit/d7073d416f5e48befad443a8e7f36e0fea1c6ce3 . 

It's a bit hack-ish and has no tests though.

**Comment by martyngigg** [comment]
@mducle Thanks. It'll be a good starting point.
