### ISSUE TITLE
Make slice viewer use CutMD

### ISSUE THREAD

**Issue by EltayebAhmed** [mantidproject/mslice#15]
MSlice currently accepts binning parameters from the users in the format `Axis, start, end, size of step`. However the underlying mantid Algorithms (namely `SliceMD`) use the format `Axis, start, end, Number of steps`. The conversion between the two formats is currently handled by mslice.
There is an algorithm in mantid called `CutMD` which is similar in effect to  `SliceMD` but accepts binning parameters in the format `Axis, start, end, size of step`. It was not used because it crashes when run with on a workspace with less than 3 dimensions (currently mslice deals with 2 dimensional workspaces).  
This duplication of functionality across mslice and mantid may lead to inconsistency between mantid and mslice if one of them is changed without updating the other.

**Comment by martyngigg** [comment]
Slice and Cut algorithms now exist.
