### ISSUE TITLE
Cut parameters cache bugs

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#172]
There are several bugs associated with this issue, all to do with the behaviour of the cut parameters caching feature which is supposed to remember previously entered values of the start, end, step size and integration ranges of a cut.

1. If the workspace is renamed, the cached cut parameters are lost. If a workspace is renamed to a previously existing workspace, its cached parameters are used instead of the correct ones.
2. After setting the parameters for one type of cut, selecting a new workspace which is of the same type (e.g. Q-E) but has not had its cut parameters set, should copy the set parameters of the previously selected workspace onto the newly selected workspace. This does not work if a non-cut workspace is selected in the mean time - but it should do.
3. If the user has just selected a workspace but have not set the parameters, this "empty" set of parameters is remembered, which disables the parameter copying mechanism above - this behaviour should be modified so that "empty" parameters are not remembered.

Issue 2 and 3 can be addressed by changes to the current code. However, issue 1 would need a large refactoring - because at present the `CutPresenter` where the cached parameters are stored (in a `dict` indexed by the workspace name) does not know about the `Rename` operation (handled by the `WorkspaceManagerPresenter` and `WorkspaceProvider`). 

The simplest option is to modify `WorkspaceProvider` (a model) to know about `CutPresenter` (a presenter) and to `pop` the dict entry when a workspace is renamed. However, this is against MVP principles since the model would change a property of a presenter.

Perhaps the most elegant option is to use the new `*Workspace` wrapper classes designed for the CLI to store the cached information. This is access via `WorkspaceProvider` to which all the presenters currently have access. This option might have to wait until after further work on the CLI is completed.

**Comment by martyngigg** [comment]
@mducle I think what we are certainly missing is a basic data class that just stores the cut information. I like the idea of using the workspace wrappers as it keeps things together.

**Comment by mducle** [comment]
@martyngigg Ok. I've created a new issue - #178 - for the future refactoring when the CLI code is mature enough and will not change.

For the moment, I've refactored it so that the cached cut parameters are stored in `MantidWorkspaceProvider` instead of `CutPresenter` so that renaming workspace won't break the cached parameters.
