### ISSUE TITLE
Refactor specific cut/slice functions in PlotFigureManager

### ISSUE THREAD

**Issue by MatthewBowles** [mantidproject/mslice#186]
Currently, the `PlotFigureManager` class in `plot_figure` is used for both cut and slice figures, but many of its methods only apply to one or the other. The two types of figures are growing increasingly disparate (and complex) so the code should be separated. `PlotFigureManager` should only contain shared functionality.

Creating subclasses for each type is inconvenient since the type of figure is not known when it is created. Therefore, specific functionality should be moved into new classes (one for slices and one for cuts) which will be created inside `PlotFigureManager`.

This will make it much easier to extend and improve in the future.

**Comment by martyngigg** [comment]
:+1: This is a good idea.

Can you provide a rough sketch of the class layouts and methods before starting?

**Comment by MatthewBowles** [comment]
@martyngigg I was thinking something like this:

![mslice_plot_figure](https://user-images.githubusercontent.com/29917114/33480218-45213a08-d688-11e7-8c84-f341a3549b9e.JPG)

Currently, the slice plotter calls the `add_slice_plotter` method on the `plot_figure`, which is where slice specific connections and members are set up. I want to replace this with an `add_slice_plot` method that creates a new `SlicePlot` object and stores it as a member of `PlotFigureManager`. This will handle all of the slice specific code, so that `PlotFigureManager` doesn't need to worry about which it is. This setup will be mirrored for cuts.

**Comment by martyngigg** [comment]
@MatthewBowles :+1: Sounds reasonable to me. Are there any good ways we can maximise the amount of test code we can wrap around these new types?

**Comment by MatthewBowles** [comment]
The existing methods in plot_figure are hard to test since `PlotFigureManager` is a `QtPlotWindow`. Moving them into the new classes will allow them to be tested (by mocking out `PlotFigureManager`)
