### ISSUE TITLE
Investigate options for default colour map

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mslice#20]
What should the default colour map be?

Matplotlib 2.0 will have `viridis` has the default colour map - http://bids.github.io/colormap/. Should we choose this as the default now?

**Comment by mducle** [comment]
Viridis is fine as a default. 

I would also like to add the other two perceptually uniform color schemes `plasma` and `inferno` (there is another `magma` but it seems almost identical to `inferno` - see http://matplotlib.org/examples/color/colormaps_reference.html).

Also, I would also like to add `cubehelix` which is an older (almost) perceptually uniform colormap from the Astrophysics community which is based on a rainbow colormap, and the sequential colormaps `hot` and `gray` (and maybe `bone`).

**Comment by martyngigg** [comment]
Decisions already made and implemented.
