### ISSUE TITLE
Cannot load SNS reduced nxs file

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#216]
Reported by an SNS user that MSlice cannot load SNS `nxs` reduced files (but loads `nxspe` files). Suspect that it is because the `nxs` file is a Mantid `MDEventWorkspace` rather than a `Workspace2D`.

**Comment by MatthewBowles** [comment]
To clarify, is this a problem with the actual `Load` operation? You should be able to load `MDEventWorkspace` files, but there is an error when attempting to display them - MSlice assumes there is no `ExperimentInfo` because of a bug in `SliceMD`.

**Comment by mducle** [comment]
The load and projection operations happens ok, but when displayed, the plot shows the wrong intensity.
The input data is an `EventWorkspace` (not `MD`). I think possibly it's using the wrong options for `ConvertToMD`. I'll investigate a bit more and update the comment.
