### ISSUE TITLE
MSlice not compatible with Qt5

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#218]
When run on a system with `pyqt5`, MSlice fails to load a workspace.

**Comment by martyngigg** [comment]
Should remove qtpy in `https://github.com/mantidproject/mslice/blob/master/mslice/util/qt/QtCore.py` until everything is sorted?

**Comment by mducle** [comment]
This was reported using the `conda` installation of the Mantid framework. In this case, there is only `pyqt5` which means that without `qtpy`, MSlice would not run at all.

**Comment by martyngigg** [comment]
Ok. I guess the quickest thing is to just find the places, there shouldn't be too many, that need to do things differently and update them.
