### ISSUE TITLE
Background subtraction

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#221]
This is a feature which was rated a high priority by users during a meeting in Jan 2018.

**Subtraction should only be allowed for just-loaded workspaces (e.g. reduced data only, not rebinned data)**

There should a `Subtract` button on the reduced data tab (labeled "Histo DE/Pixel" on the GUI design pdf), which when clicked should give a popup window where the user can select the background workspace. Clicking ok would then create a new workspace using the following algorithms:

```
Scaled_Background_Workspace = Scale(Background_Workspace, SSF)
OutputWorkspace = Minus(LHSWorkspace=Selected_Workspace, RHSWorkspace=Scale_Background_Workspace)
```

Where `Selected_Workspace` is the workspace(s) the user selected before clicking `Subtract`, and `Background_Workspace` is the workspace selected in the popup window. `SSF` is the self-shielding factor and should be obtained from an input text box (default to `1.0`) in the popup window.

So, the work-flow should be:

1. User selects one or more workspaces from the workspace list
2. User clicks `Subtract`
3. A pop up window with a help text ("Please select the background workspace to subtract"), a text box for the self-shielding factor and a list of the possible workspaces (which is all reduced workspaces) for the background from which the user can select one. The user enters a self-shielding factor, selects a workspace, and clicks `OK`.
4. If the selected background workspace is valid, calculate `Scaled_Background_Workspace`, and:
  a. If the user originally selected a single workspace, a single output workspace is produced which has the name of the original workspace with "_subtracted" appended.
  b. If the user originally selected multiple workspaces, loop over the workspaces and for each subtract the scaled background workspace and produce a new "_subtracted" workspace.

**Comment by MatthewBowles** [comment]
Thanks @mducle. Is the `Add` button related to this?
