### ISSUE TITLE
Warn users before attempting to slice to extreme binnings

### ISSUE THREAD

**Issue by EltayebAhmed** [mantidproject/mslice#28]
I tried to display a slice with a total number of bins in the range of 10^8
As expected the computer came to total freeze (had to forcefully shutdown from power button).
It would be a good idea to warn the users before trying plot unreasonable (slices/plots)
@martyngigg any suggestions on the number of bins where we should start trying to warn the user?

**Comment by EltayebAhmed** [comment]
@martyngigg  any input? I think should be addressed before people start installing and testing mslice on there machines.

**Comment by martyngigg** [comment]
I agree that it makes sense to warn users of the danger. It's probably worth doing a couple of tests to see on your own machine where the choke point is. I would hazard a guess that something like warning if the number of bins > 10^5 would be more than enough.

**Comment by mducle** [comment]
After discussions with Ross and Helen, we think the best approach is if `mslice` can detect the smallest bin size in the data and not allow binning smaller than this value (e.g. if the user demands a smaller bin size, it should return a cut with the minimum bin size and (re)set the value in the input box to this smallest bin size).

**Comment by mducle** [comment]
Fixed by PR #120
