### ISSUE TITLE
Non-PSD mode remember cut axes

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#297]
In Non-PSD mode, changing workspaces switches the `Slice`/`Cut` tab back to `Slice` even if you were on `Cut` before and the new workspace is also of non-PSD type. It also switches the integration axes back to the default (`DeltaE`) regardless of the previous setting, but remembers the previous "along" axis. This means that if the previous axis is `DeltaE`, both the cut and integration axes are `DeltaE`. To see this do:

1. Open a two **Non-PSD** data files (e.g. `MAR21335_Ei60.00meV.nxs` and `MER30936_Ei10.00meV.nxspe`).
2. Select one of the files and click on the `Cut` tab. Change the cut axis (`along`) to `DeltaE` and check that the integration axis (`over`) changes to `|Q|`. 
3. Put in some numbers (e.g. `from` -5 `to` 5 with default steps, integrating `from` 0 to 10) and plot.
4. Now select the other file in the workspace list, and then select the previous file again. You'll see that on selecting another workspace that the focus moves back to the `Slice` tab.
5. Click again on the `Cut` tab. See that the cut axis (`along`) is still correctly set to `DeltaE`; but the integration axis (`over`) has been reset to the default `DeltaE` also, so both axes are `DeltaE` although the cuts still work (just the legend title is now wrong).

The desired behaviour is that if the `Cut` tab is selected and a new workspace is then selected that the GUI should stay on the `Cut` tab and keep the same cut/integration axes, and cut parameters if no previous cut parameters are given for this workspace, and switch to the previous cut parameters if there exists previous parameters (this is the behaviour for "PSD" mode).

**Comment by MatthewBowles** [comment]
I can take a look at this.

@martyngigg If this is a patch candidate won't we need another PR in the mantid repo?

**Comment by mducle** [comment]
@MatthewBowles Thanks!
@martyngigg I don't think it needs to get into the nightly build. Getting it into the patch will be ok I think. 

I've nearly finished the documentation. 

I was about to then send all the instrument scientists at SNS and ISIS an email asking them to try it out and give feedback. However, if the patch release is going to come out quite soon then perhaps I should wait until it is out to do this? Or should I send it and ask them for quick feedback so we can try to put changes into the patch? (That doesn't seem so feasible to me, for testers and developers both!)

**Comment by martyngigg** [comment]
@mducle Given the upcoming Easter break I think we're looking at mid April for the patch. I'd say anything we want to get into a patch should not really need testing too much or at all by others as it should be just bug fixes really.

**Comment by MatthewBowles** [comment]
@mducle I'm having trouble reproducing this... It does change to slice when selecting a different workspace, but the cut tab axes seem to both return to defaults (|Q| and DeltaE).
