### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mslice#33]
The main view presenter has a test coverage much less than the threshold 80%. The main view presenter should have very good coverage based on how important it is to the operation of mslice.

Also, can you start slowly increasing the test coverage limits. Raise it as you improve the test coverage.

**Comment by EltayebAhmed** [comment]
This has been addressed in pull request #31 and the new coverage is 100%

**Comment by OwenArnold** [comment]
@EltayebAhmed Excellent. Then make sure you increase the limit in the `.travis.yml` file. I don't see that that PR has make the threshold any more strict.

**Comment by OwenArnold** [comment]
After that you can close this Issue.

**Comment by EltayebAhmed** [comment]
@OwenArnold  In addition to failing builds with coverage < 80, 
Coveralls will fail any build which decreases the coverage of any module that has cover checks enabled. Adding new code which is not executed by existing tests will fail the build unless new tests are added.
With this in mind I don't think it would make sense for me to increase the limit from 80 to 83, I will probably increase to 90% when i get there though.

**Comment by OwenArnold** [comment]
Ok. In that case I'll close this issue.
