### ISSUE TITLE
Keep figure functionality in CLI

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#396]
There should be a way to programatically "keep" or "make current" a figure using the command line interface.

Example syntax:

```
import mslice.cli as mc

ws = mc.Load('data.nxs')
mc.PlotSlice(mc.Slice(ws, '|Q|', 'DeltaE'))
mc.KeepFigure()   # Without arguments means it should apply to the last figure plotted.
mc.PlotSlice(mc.Slice(ws, 'DeltaE', '|Q|'))
```

This should produce two slice plot windows, with the second one showing the data transposed with respect to the first one.

In order to enable book-keeping, the `PlotSlice` and `PlotCut` commands should also return the integer number of the plot window, e.g.:

```
hcs = mc.PlotSlice(mc.Slice(ws, '|Q|', 'DeltaE'))
hcc = mc.PlotCut(mc.Cut(ws, 'DeltaE'))

mc.KeepFigure()   # Sets hcc to "kept" (not hcs)
mc.KeepFigure(hcs)
hcs2 = mc.PlotSlice(mc.Slice(ws, 'DeltaE', '|Q|'))

mc.MakeCurrent(hcc)
mc.PlotCut(mc.Cut(ws, 'DeltaE', '|Q|,0,2'), PlotOver=True)
```

This would also allow a `MakeCurrent` command too.

**Comment by aybamidele** [comment]
@martyngigg what do you think of this issue in relation to the mslice projection we're making

**Comment by aybamidele** [comment]
@mducle I have included this feature request as part of #404. While it is still in progress, I believe you can test the functionality in the pull request.

**Comment by mducle** [comment]
@aybamidele Thanks Andre! It works really well!

**Comment by aybamidele** [comment]
@mducle Is it okay to close this issue?

**Comment by mducle** [comment]
@aybamidele Sure!
