### ISSUE TITLE
MSlice CLI does not work in MantidPlot unless the interface is activated first

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#401]
Trying to use the MSlice CLI in either the script window (activated by `F3`) or script interpreter without first lauching the interface (from the `Interfaces -> Direct` menu) gives an error on `load_workspace`, because this function (in addition to loading a file) also handles some GUI tasks - such as switching tabs from the `Data Loader` to the `Workspace Manager` and thus assumes that the `MAIN_WINDOW` has been created.

Since loading data is the first step in using MSlice, this means that the CLI cannot be used unless the GUI window is first activated. For the stand-alone version of MSlice we can safely assume that the GUI window will always be there, but when running from MantidPlot, this may not be true.

There is a design decision to be made here:

1. Catch all instances where current functions assume that the `MAIN_WINDOW` is needed but has not be created and create it (e.g. when running `mc.Load` from the CLI it would pop up the GUI if the GUI has not been opened).

2. Separate out GUI from non-GUI parts of algorithms / functions which currently do both like `Load` (e.g. when running `mc.Load` the GUI will not be accessed, but clicking on a file and on the `Load Data` button will first call the (non-GUI) `Load` algorithm and then call another internal function to modify the GUI [to switch to the Workspace Manager]).

**Comment by martyngigg** [comment]
From the perspective of the code we can of course do either. We did make the assumption that the CLI was "scripting" modifying the GUI as if you'd pressed buttons. What workflow would be best for users? When would they expect to see to GUI or indeed would they? Would it be better to have a `matplotlib`-style` show so that the GUI only pops up when requested?

**Comment by aybamidele** [comment]
@martyngigg Is it safe to delete this as it has been solved in #412 ?

**Comment by martyngigg** [comment]
@aybamidele Rather than deleting it we should add it to the list of issues closed by #412. You can have multiple issue references in pull requests

**Comment by martyngigg** [comment]
This is fixed in #412 as long as the script interpreter has the `Execute` mode set to `Serialised`. There is still bug #400 to figure out.
