### ISSUE TITLE
Add CLI `ConvertTo*` algorithms for the different intensity options

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#402]
It would be nice to have algorithms for the CLI which has the functionality of the `Intensity` menu options in the slice plot windows, e.g.

1. `ConvertToChi` - converts to the dynamical susceptibility `Chi''(Q,E)`
2. `ConvertToChiMag` - converts to the magnetic dynamical susceptibility `Chi''(Q,E magnetic`
3. `ConvertToCrossSection` - converts to the double differential cross-section `d2sigma/dOmega.dE`
4. `SymmetriseSQE` - converts to symmetrised S(Q,E) (w.r.t. energy using temperature Boltzmann factor) 
5. `ConvertToGDOS` - converts to the generalised density of states

In addition, it would also be good to have a GUI wrapper around the Mantid algorithm `ComputeIncoherentDOS` - e.g. when doing a cut along energy, can specify whether to cut the data or to cut the data and convert to DOS using this algorithm.

**Comment by aybamidele** [comment]
@mducle You can find the first part of this issue in #404.

**Comment by mducle** [comment]
:thumbsup: Thanks @aybamidele
