### ISSUE TITLE
Flip Axis button not working properly in interactive cut mode with multiple icut windows open

### ISSUE THREAD

**Issue by aybamidele** [mantidproject/mslice#403]
To reproduce the Issue:
Plot a slice
Plot a cut using interactive cut
Turn interactive cuts mode off
Mark the cut as kept
Plot a cut using interactive cut mode again
Mark the first cut as current
Then try to flip the axis in the old one, you get this:
AttributeError: 'NoneType' object has no attribute 'flip_axis'
Also, the flip axis button on the new cut window affects the old one and not the new one which it is on.

**Comment by mducle** [comment]
On the latest master going through the steps outlined in the issue (plot interactive cut, keep it, and then plot another interactive cut) does not give an attribute error but rather flips the axes of the figure which is "current" and changes its mode to an interactive cut - e.g. there are now two interactive cut windows. When interactive cut mode is switched off, the first interactive cut window's mode does not change.

It would make more sense to only allow a single interactive cut window by disabling the `Keep`/`Make current` buttons whilst an interactive cut is active.

**Comment by mducle** [comment]
Fixed in #450
