### ISSUE TITLE
MSlice CLI in MantidPlot incompatible with mantid.simpleapi

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#416]
To reproduce this you need to use the `master` branch of MSlice in a MantidPlot installation - e.g. git checkout master and then copy the `mslice` folder to `$MANTIDINSTALL/scripts/ExternalInterfaces/mslice`.

1. Start MantidPlot
2. Run a command using an algorithm from `mantid.simpleapi` with a syntax specific to `simpleapi` - e.g. `Load('MAR21335_Ei60.00meV.nxs', OutputWorkspace='MAR21335')`
3. Start up the MSlice interface (Interface -> Direct -> MSlice).
4. Try to run the previous command again - it should give an error about not understanding `OutputWorkspace`.

This is due to a name collision between the MSlice and `simpleapi` algorithms for `Load` - but also all other `simpleapi` algorithms will give an error if run with the `StoreInADS` keyword set, and also the output of these algorithms will not appear in the "Workspaces" tab.

This is because MSlice wraps all algorithms so that they know about MSlice type workspaces. However, it then pushes these wrapped algorithms to the `global` namespace, overwriting the `simpleapi` versions - to overcome this, scripts would have to use something like `from mantid.simpleapi import *`, to re-overwrite MSlice versions. 

I suggest changing `util/mantid/mantid_algorithms.py` to check if we're running inside MantidPlot, and if so to use the wrapped algorithms within the `mslice.cli` namespace only rather than the global namespace.

**Comment by martyngigg** [comment]
Yes, thinking about this some more and this was not such a good idea. I'll have a look at this.

**Comment by martyngigg** [comment]
I guess the big problem here is that we have the workspace wrappers and it could be confusing that one package gives a standard workspace and another command of the same gives something very similar but not the same. I'll have a think on this.
