### ISSUE TITLE
Ability to call powder - Calculate Projection

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mslice#445]
After loading the workspace it looks like this:
![image](https://user-images.githubusercontent.com/24723609/53742269-2a747a00-3e90-11e9-9261-8648357ddfc9.png)

Then I select MDEvent:
![image](https://user-images.githubusercontent.com/24723609/53742302-3d874a00-3e90-11e9-9347-5509b741a08d.png)
(Notice how it stayed on the slice menu)

Then I switch back to 2D and select the same workspace:
![image](https://user-images.githubusercontent.com/24723609/53742357-5d1e7280-3e90-11e9-8269-b90605564ba6.png)

I can select Calculate Projection.

Clicking this causes a runtime error and a crash.
![image](https://user-images.githubusercontent.com/24723609/53742402-732c3300-3e90-11e9-88c7-56b38cc5b07c.png)

Perhaps better handling of errors should be considered alongside fixing the cause of this.

**Comment by aybamidele** [comment]
@Pasarus I appreciate the pictures! Thank you so much for them!

**Comment by aybamidele** [comment]
@mducle Is it okay to close this?
