### ISSUE TITLE
Unhandled exception when cancelling save on sliced plot

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mslice#447]
After slicing a workspace and displaying it, I clicked on the save icon, which pops up a window to save it:
![image](https://user-images.githubusercontent.com/24723609/53746085-5c89da00-3e98-11e9-9e2b-02051e8a67f0.png)

Then when I click cancel I get the unhandled exception:
![image](https://user-images.githubusercontent.com/24723609/53746237-ab377400-3e98-11e9-8a79-70566b2b71bb.png)

**Comment by aybamidele** [comment]
@mducle Is it okay to close this?

**Comment by mducle** [comment]
Fixed in #450
