### ISSUE TITLE
MantidPlot crashes when generated slice script is run.

### ISSUE THREAD

**Issue by aybamidele** [mantidproject/mslice#464]
Steps to reproduce issue:
Open Mslice from within MantidPlot (Interfaces -> Direct -> Mslice)
Load this test data [MAR21335_Ei60.00meV.zip](https://github.com/mantidproject/mslice/files/3038740/MAR21335_Ei60.00meV.zip) and plot a slice.
In the file options, click generate script.
Try to run the python file in the CLI within MSlice or in the script window.
MantidPlot Crashes

It is worth mentioning that if you perform the steps above within MSlice without running MantidPlot, you do not get a crash.

**Comment by mducle** [comment]
Further investigations show that this is due to the workspace overwrite confirmation dialog - possibly some kind of QT thread issue. Work around would be to ignore the dialog if running in a script...
