### ISSUE TITLE
Improve Energy axis binning suggestion

### ISSUE THREAD

**Issue by EltayebAhmed** [mantidproject/mslice#48]
Currentl MSlice will come up with suggestions for plotting a slice when the user clicks on a sliceable workspace. The suggestions for the range of an azis are to the span of the data along that axis. The suggestions for the bin size is calculated by `range/100`. For the `|Q|` Axis this is OK. For the energy axis a more intelligent guess can be made. 
To be more specific, energy axis binning should suggested as the coarsest bin in the original data (if this data is not available the workspace it is known as a fact that it is in the .nxs file)

**Comment by mducle** [comment]
Fixed in PR #120
