### ISSUE TITLE
Qt deadlocks when running a script using `import` from MantidPlot/Workbench

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#497]
### To reproduce

Run MSlice through the Interfaces->Direct menu in MantidPlot or the Workbench. Load a data file and make a plot (e.g. click `Display`). Go to File->Generate script and create a python script which should reproduce the plot.

`import` that script in the IPython console.

MantidPlot or Workbench will hang.

### Investigations

MantidPlot/Workbench is hanging because of this call: https://github.com/mantidproject/mslice/blob/master/mslice/util/qt/qapp.py#L54 which causes Qt to deadlock somehow (running gdb shows that the code is stopped in a thread waiting state (`do_futex_wait` in `libpthread` on Linux)). 

If you comment out all lines in the script and run the `import`. Then uncomment them and run `reload` then the script executes fine.

Running the script in the Python window also works ok, so it's something to do with the handling of `import`s.

Changing the `Qt.BlockingQueuedConnection` to `Qt.QueuedConnection` stops MantidPlot / Workbench hanging but also means that the code no longer works (it never executes the thread call and instead returns `None`).

**Comment by srikanthravipati** [comment]
@mducle @SilkeSchomann I do not think this is an issue anymore!

**Comment by SilkeSchomann** [comment]
After checking this on IDAaaS I agree. Although there is an error message the plot is reproduced correctly.

**Comment by mducle** [comment]
Yes, I think some changes in Mantid has fixed this issue.
