### ISSUE TITLE
Create installer for MSlice

### ISSUE THREAD

**Issue by EltayebAhmed** [mantidproject/mslice#5]
Currently mslice has no installer. For mslice to run it requires mantid, python 2.7 and matplotlib >1.5.1. the latter two come with mantid (however on `RHEL 6` mantid ships with matplotlib 1.3 and will not run mslice properly).
There currently is a branch called `startup_scripts`. These scripts contain scripts to start mslice with an ipython shell with event loop integration. These scripts contain hardcoded paths to the `mantidpython` script in mantid.If users have installed mantid to an directory other that the default suggested by the the mantid installer these scripts will not work. An installer for mslice should verify that it can find `mantidpython` in the default paths, if not it should (ask the user to show where they installed mantid/ deduce correct path)

**Comment by martyngigg** [comment]
Commits here have the wrong reference number.

It is unclear whether an installer is now necessary or if this will just be included in the Mantid distribution.
