### ISSUE TITLE
Overplot doesn't work on slice plotted from script within MantidPlot/Workbench

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#505]
### To reproduce

Open MSlice in MantidPlot or Workbench. Plot a slice and save a script from the plot window. Close the window, open the saved script and run it - another window with the same plot should appear. Go to the `Information` menu option and try to plot any recoil line or Bragg peaks - nothing appears on the plots. 

### Analysis

This bug does not appear if the script is run from the command line or `import`ed into a standalong MSlice session (outside MantidPlot / Workbench) - e.g. the `Information` overplot lines appear in a plot window created from a script. It is probably also an issue with Matplotlib threads like the waterfall issue.

**Comment by srikanthravipati** [comment]
@mducle @SilkeSchomann This may not be an issue anymore, unless I missed something. Could you please check?

**Comment by SilkeSchomann** [comment]
I've tried to reproduce this issue on Mantid 5.1 without success.

**Comment by mducle** [comment]
Yes, I think this issue has been solved by changes in Mantid in the mean time. I think it was originally found on Mantid 4.(something)... it's been a while ;)
