### ISSUE TITLE
Issues found in Unscripted Testing Release 4.2

### ISSUE THREAD

**Issue by hsautessella** [mantidproject/mslice#511]
A few issues found during unscripted testing https://github.com/mantidproject/mantid/issues/27143, I don't know that any are important for the upcoming release:

- When you click refresh in the Data Loading tab, the "Date Modified" and "Size" column switch around.
- The text does not fit inside the "Save to Workbench" button on the MD Histo tab

<img src=https://user-images.githubusercontent.com/46960113/67773394-91fcbc80-fa53-11e9-9dc7-4210b32e0686.png width=30%>

- Error reporter pop-up when trying to load a GroupWorkspace (e.g. LARMOR00003368 in unit test data).
- Braces not closed on plot units when setting the intensity to Chi''(Q, E) Magnetic

![image](https://user-images.githubusercontent.com/46960113/67774460-506d1100-fa55-11e9-98c6-a7cb4bdc9434.png)

- The print button on the plot toolbar did not seem to do anything

- When saving an image, the default format in the file window is .nxs

- If you plot a slice and add some information (e.g. Bragg peaks), then you change the colormap, the Bragg peaks will disappear, but the Bragg peaks will still be checked in the "Information" menu.

- Deleting a workspace in the main Workbench GUI does not remove the workspace from MSlice. Clicking the deleted workspace in MSlice raises the error dialog.

- Sometimes when you attempt to load a file, an error message will be written to the bottom of the MSlice window saying "MSlice was not able to load the selected file". However, the file is loaded into the Workspace Manger tab, but you cannot perform any Powder/Slice/Cut operations on it.

**Comment by DanielMurphy22** [comment]
I can recreate all of these problems. The intensity unit change can be rather slow.

The loading errors produce error report pop-ups in Workbench but not in MantidPlot where the data is still not loaded and still no reason is provided.
A successful file to load is MAR21335_Ei60meV.nxs in ExternalData/Testing/Data/UnitTest

To reproduce the last problem I used LOQ48127.nxs in ExternalData/Testing/Data/UnitTest

**Comment by mducle** [comment]
I've fixed most of the listed problem, but:

* I can't reproduce the print issue - I've tried on a local Ubuntu 16, Windows 10 and RHEL 7 machines as well as IDAaaS and they all give the print dialog.
* Removing a workspace from the MSlice list after it's been deleted in the main workbench is tricky... I don't want to set up polling of the ADS but there doesn't seem to be a hook into the ADS @martyngigg do you have any idea?
