### ISSUE TITLE
MSlice Unhandled ValueError exception when rename cancelled

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mslice#542]
**Original reporter:** David Voneshen via Error Reporter

### Expected behavior
When renaming a file in the MSlice interface, clicking cancel should close the dialog box and not cause an error

### Actual behavior
An error is thrown when the rename dialog box is closed

### Steps to reproduce the behavior
1. Open the MSlice interface (Direct -> MSlice)
2. Load a file (e.g. 164198.nxs from the training data)
3. Click rename to open the dialog, then click cancel

### Platforms affected
Confirmed on windows, assumed on all

**Comment by AnthonyLim23** [comment]
@sf1919 is the bug you found?

**Comment by sf1919** [comment]
Yes this is the error I found. Below is a screenshot of the error message I'm getting on it crashing when I click cancel from the Add dialog box.
![error2](https://user-images.githubusercontent.com/55837273/93317177-0e7fc180-f805-11ea-8cdb-1fbaddf672c3.png)
