### ISSUE TITLE
Error message for Ignored Exception and Runtime error when creating slice/loading files

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mslice#544]
As found during Beta testing

**Expected behaviour**
When creating a slice the messages should show successful Slice, Transpose and DeleteWorkspace.

**Actual behaviour**
After a successful slice an Ignored Exception and Runtime error occurs before as successful Transpose. User was accessing MSlice through IDAaaS.

![Mslice_error](https://user-images.githubusercontent.com/55837273/93321263-ea72af00-f809-11ea-80eb-d6bb79ff6343.JPG)

**Steps to reproduce**
It was not possible to reproduce this error. However the same error occurred when trying to open a file in MSlice with the same name as an existing workspace and choosing to overwrite it.

The steps to recreate this error are as follows
1) Open MSlice
2) Load file e.g. MAR21335_Ei60.00meV.nxs
3) Load file with same name but different file extension e.g. MAR21335_Ei60.00meV.nxspe
4) Click ok when Alert appears about Workspace name already being used and do you want to overwrite it
5) Error message appears in messages as per screenshot below

![error1](https://user-images.githubusercontent.com/55837273/93321620-463d3800-f80a-11ea-8d4a-392ac019b591.png)

**Platform affected**
Original issue involving taking slices found on IDAaaS Workbench Nightly version during Beta testing on 14/09/2020

Similar issue found when overwriting the Workspace occurred on Windows 10 using Mantid Nightly 5.1 version from 09/09/2020

**Comment by sf1919** [comment]
Discussed with @martyngigg and decided this is a low priority as does not crash Mantid and in the case of taking a Slice does not appear to interfere with or affect the resulting plot. Therefore does not need to be fixed for Mantid 5.1 release,

**Comment by SilkeSchomann** [comment]
The fix for https://github.com/mantidproject/mslice/issues/528 also fixes the runtime error described above. However, when following the steps to reproduce the problem the same runtime error is triggered in a different part of the code:

**Comment by srikanthravipati** [comment]
Perhaps 5693a3fb77982701c9fa88a70d781aae1ef8a984 could be an inspiration; use of ``try`` and ``except``
