### ISSUE TITLE
Add ability to change font size of main GUI text

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#554]
On current IDAaaS the fonts in the main GUI of MSlice is very small. We should increase it and give users the option to change the font size in the GUI.

**Comment by SilkeSchomann** [comment]
@mducle It is already possible to change the font size of the GUI via Mantid when MSlice is running as an interface. Is this meant to be available for the standalone version as well?

**Comment by mducle** [comment]
Thanks. I just verified this - I don't know if this was possible when this issue was raised - also the default font size (8? at least it was that for me) looks ok now. 

However, we may need to document this a bit more.

**Comment by SilkeSchomann** [comment]
I agree. We could probably add a paragraph to 1.1. Starting MSlice in the documentation on how to change this for MSlice as a Mantid interface and that the setting is only applied after a restart of Mantid.
