### ISSUE TITLE
Edit dialog box for x range does not open again when Logarithmic selected

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mslice#557]
**Expected behavior**
The Edit x range dialog box should open again after changing to a logarithmic scale, clicking the Ok button and double-clicking on the x axis.

**Actual behavior**
The Edit x range dialog box does not open again properly after changing to a logarithmic scale, clicking the Ok button and double-clicking on the x axis. The dialog box window remains empty and closes again instead.

**Steps to reproduce the behavior**
1. Open MSlice.
2. Load any data 
3. Go to the Workspace Manager tab
4. Click on the Cut tab and then on Plot.
5. Open the Edit x range dialog box by double-clicking on the x axis.
6. Select Logarithmic and click on the Ok button.
7. Re-open the Edit x range dialog box by double-clicking on the x axis.

**Comment by srikanthravipati** [comment]
@SilkeSchomann Could you please check if this is still an issue?

**Comment by SilkeSchomann** [comment]
I can still see this problem on IDAaaS with Mantid 6.0.

**Comment by srikanthravipati** [comment]
Oh okay. I can't seem to reproduce it on my windows machine.

**Comment by SilkeSchomann** [comment]
It seems to be Linux-only. I cannot reproduce it on windows either.
