### ISSUE TITLE
Feature request: Powder peaks in 1D cuts in Q/2theta

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#602]
At the moment you can do an "Information overplot" on 2D slices, which includes recoil lines and powder lines.

Recoil lines don't make sense for 1D plots, but powder lines (peak positions in |Q| or 2theta) do make sense and would be a useful additional functionality.

Original suggester: @tatgu

**Comment by srikanthravipati** [comment]
@SilkeSchomann @mducle @TatGu
When a powder peak over-plot is requested on a cut plot (window), the parent workspace that corresponds to the first cut
on the plot- window https://github.com/mantidproject/mslice/blob/95b65e366c2913e9e6598fe0e8bbb2f575f038bf/mslice/presenters/cut_plotter_presenter.py#L98 is used to compute powder lines and plot them. 

Do the powder peaks depend on the workspace? For example, if there are cuts from different workspaces on a cut plot, and powder peaks are requested would it be okay
to pick any workspace or there should be powder peak per workspace (per element)?

On a more general note, are the cuts on a cut plot window homogeneous (are all the cuts from the same workspace) usually?
