### ISSUE TITLE
Implement energy unit conversions

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#63]
In the calculate projections tab there is an option for different energy units. This is one of the key requirements of the Molecular Spectroscopy group because they tend to use *wavenumbers* `cm-1` rather than `meV`. 

The conversion factor is 1meV = 8.06573cm-1

**Comment by EltayebAhmed** [comment]
So I should scale the Energy (typically x axis,  right?) by that factor?

**Comment by mducle** [comment]
Yes. But actually, I think you can use the `ConvertUnits` algorithm - we want conversion between `deltaE`  (which is in meV) and `deltaE_inWavenumber`. This would keep track of which units the workspace is in...
