### ISSUE TITLE
Slice scripts do not work

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mslice#630]
Open MSlice and load some data
Plot a slice
On the plot select "generate script to clipboard" 
Past the script and try to run it - it will fail

**Comment by SilkeSchomann** [comment]
This is can only be reproduced on Linux.

**Comment by AnthonyLim23** [comment]
maybe the lib is not installed or the command is deprecated?

**Comment by SilkeSchomann** [comment]
It looks as if 'Generate script to clipboard' does not copy to the clipboard on Linux. When testing on Windows before, the script created on Windows is still in the clipboard but cannot run on Linux as the file path is incorrect for Linux. It becomes obvious when different content is copied to the clipboard. The script generation as such is working fine. With 'Generate Script File' the generated file works fine.
