### ISSUE TITLE
Enable loading of indirect geometry datasets.

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#65]
We would like to support both the direct geometry spectrometers (LET, MAPS, MARI, MERLIN) as well as the indirect geometry spectrometers (IRIS, OSIRIS, TOSCA). This means that calculate projection should enquire if the input datafile (workspace) has Emode `Direct` or `Indirect` and pass it to ConvertToMD.

**Comment by EltayebAhmed** [comment]
Is it ok if push a slight tweak to this branch? We dont use `mtd` in MSlice. This is abstracted away (Hopefully it will make life easier when the ADS is phased out)
