### ISSUE TITLE
Update pyplot to MPL3 needed.

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#693]
**Describe the bug**

While testing #692 on Windows, where Mantid ships with Matplotlib 3.1.2, running the example script in the issue that PR fixes (#686) gives this error:

```python
~\src\mslice\mslice\plotting\pyplot.py in plot(*args, **kwargs)
   3200     # Deprecated: allow callers to override the hold state
   3201     # by passing hold=True|False
-> 3202     washold = ax._hold
   3203     hold = kwargs.pop('hold', None)
   3204     if hold is not None:

AttributeError: 'AxesSubplot' object has no attribute '_hold'
```

This is because the hold on/off and overplot functionality of Matplotlib was [deprecated](https://github.com/matplotlib/matplotlib/blob/f6e0ee49c598f59c6e6cf4eefe473e4dc634a58a/doc/api/prev_api_changes/api_changes_2.0.0.rst#hold-functionality-deprecated) in Matplotlib 2 and [removed](https://github.com/matplotlib/matplotlib/blob/7443d8842a0e613b36f97d945ecaad18aadad15f/doc/api/prev_api_changes/api_changes_3.0.0.rst#hold-machinery) in Matplotlib 3. On RHEL7 / SL7 used on DAaaS the system Python (3.6) still uses Matplotlib 2.2.3 and the `pyplot.py` used by MSlice was copied from Matplotlib 2 so still had the hold on/off code.

We should amend the `pyplot.py` code in MSlice so it will work with both Matplotlib 2 and 3 (we need a `try` block).

Edit: This bug was fixed in #701 with an `if` block but a longer term fix is to refactor `pyplot.py` so that we don't have such a large almost-verbatim copy of Matplotlib code.

**To Reproduce**

Run the script in #686 on a system with Matplotlib 3.

**Expected behavior**

MSlice should not give an exception and the plot curve should appear.

**MSlice Version (please complete the following information):**
 - MSlice Version: 2.3.2 with Mantid Nightly (6.2.20220127.1718) on Windows 10.

**Comment by mducle** [comment]
It might also be worthwhile checking if instead of including the large `pyplot.py` file in MSlice we can monkey patch the `pyplot.py` directly from the running Matplotlib implementation with just the changes needed for MSlice's keep/make current mechanism...

**Comment by mducle** [comment]
PR #701 fixes the problem for the release, so this issue is repurposed as a longer term maintenance task to refactor `pyplot.py`.

**Comment by SilkeSchomann** [comment]
Even on IDAaaS the matplotlib version is now 3.5.1.

**Comment by SilkeSchomann** [comment]
I think we still need an MSlice-specific pyplot to set the set_category decorators. Unfortunately pyplot does not allow us to do this via setattr. I am using a newer boilerplate script and base for pyplot (from matplotlib 3.6.2) though with fewer modifications than before now.
