### ISSUE TITLE
QT error message for MSlice conda on Windows

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mslice#723]
**Describe the bug**
When starting MSlice on Windows in a new conda environment for the first time, the following error message appears on a directory change on the Data Loading tab:

```
QAccessibleTable::child: Invalid index at: 11 0
qt.accessibility.core: Cannot create accessible child interface for object:  QTableView(0x156dc35f350, name = "table_view")  index:  61
QAccessibleTable::child: Invalid index at: 11 0
qt.accessibility.core: Cannot create accessible child interface for object:  QTableView(0x156dc35f350, name = "table_view")  index:  61
```

The error message does not re-occur after re-starting MSlice within the same conda environment.

**Expected behavior**
There should be no error message

**MSlice Version (please complete the following information):**
 - MSlice Version 2.3.1 (conda package only)

**Comment by robertapplin** [comment]
I updated my conda environment using the latest mantid nightly, and I no longer seem to get this issue.
