### ISSUE TITLE
List of displayed workspace can become outdated/invalid if users change ADS contents via Command Line

### ISSUE THREAD

**Issue by EltayebAhmed** [mantidproject/mslice#73]
The workspace list in MSlice can become outdated if the user creates/deletes/renames workspaces from the command line. 
A proposed solution would be to add a post-command ipython hook to refresh the display list after every executed command.
MSlice already uses an ipython hook (in plotting.pyplot.install_repl_displayhook). After adding the hook verify that the pyplot.install__repl_display_hook is still in place. If it not in place overplotting cuts from the GUI will not work.

**Comment by martyngigg** [comment]
Workspaces are no longer added to the ADS.
