### ISSUE TITLE
Implement Script Logging

### ISSUE THREAD

**Issue by EltayebAhmed** [mantidproject/mslice#79]
It was a requirement that the plot windows are able to export scripts that when executed reproduce the same script.
Currently in the `Make Script` menu in the plotting window clicking the `Dump to console` will cause a script to be dumped to console.
The script logging is handled by the plot window. The relevant code is in `plotting/plot_window/base_plot_window`. Any function in the `plotting/pyplot.py` file which has a visible effect is decorated with a `script_log` decorator tag. This decorator passes to the currently active window the name of the function called and references to the parameters it was called with. 
Since all plotting done via models (namely `models.slice.matplotlib_slice_plotter`  and `modes.matplotib_cut_plotter` after merging #55) now has a commandline equivelant it would make sense to implement a system where at the beginning of the model function call the the currently active window will is notified to stop logging the low level `pyplot` commands going into it, then 'injecting' the equivelant `cli` command and before returning notifying the plotting window to resume plotting.
Since plotting slice or plotting a cut with the parameter `plot_over=False` will clear the plot of of any previous input it would make sense to make the script window empty its current cache.
Since the plot window currently does not delete information about previous function calls after it becomes irrelevant (i.e. the plot is erased) combined with the fact it stores parameters to function calls to matplotlib functions (such as 2D numpy arrays)  this is currently a significant **Memory Leak**. Implementing the above changes will significantly reduce the memory leak, The only remaining memory risk after doing the afore mentioned changes will be due to the posibilty of users plotting arbitarily large arrays via the command line.

**Comment by martyngigg** [comment]
Superseded by #385
