### ISSUE TITLE
Icut spams ADS with workspaces

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/mslice#810]
**Describe the bug**
Whilst performing an `icut`, `mslice` continuously adds each individual cut to the `ADS`. Do we want to prevent such cuts from being stored in this way, perhaps only being added to the `ADS` when `icut` is deactivated?

**Comment by SilkeSchomann** [comment]
@MialLewis 
An MD Histo type workspace should only get created when you click Save Cut to Workspace on the icut plot (https://mantidproject.github.io/mslice/quickstart.html#interactive-cuts). Any MD Histo workspace can then be stored in the ADS when MSlice is used as a Mantid interface (https://mantidproject.github.io/mslice/cutting.html#saving-cuts) by clicking the Save to Workbench button either on the MD Histo or the Cut tab. 

To me this looks as if the StoreInADS=False parameter is missing for some of the algorithms used when working with icuts.

**Comment by MialLewis** [comment]
I can't what I thought caused this. Doesn't look to be the case so closing.
