### ISSUE TITLE
MSlice crashes when clicking on Delete button

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mslice#822]
**Describe the bug**
On Ubuntu MSlice crashes when clicking on the Delete button without selecting a workspace to delete.

**Comment by robertapplin** [comment]
I have tried to reproduce this with multiple workspaces loaded, and multiple cuts in the MDHist tab. I have tried clicking delete in each of the tabs with no workspaces selected and I can't get MSlice to crash. I'll close this for now as it might be a very rare edge case that happened at the end of manual testing
