### ISSUE TITLE
Saved nxs from scaled or subtracted workspaces not reloadable

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#834]
**Describe the bug**
MSlice has the ability to compute scaled or subtracted workspaces using buttons in the "Workspace Manager" tab (or via the CLI). There is also a "Save" button to save these two Nexus / `nxs` format. However, MSlice gives an error if these workspaces are loaded again.

**To Reproduce**
1. Load a datafile
2. Apply a scaling to the loaded workspace
3. Save the scaled workspace as "Nexus"
4. Load the saved `.nxs` file - MSlice will give an error

**Expected behavior**
MSlice should be able to reload the saved workspace and treat it as it would as if that workspace was the result of the processing. This likely means that additional functionality needs to be added to save the required MSlice workspace metadata in order to construct the [`Workspace`](https://github.com/mantidproject/mslice/blob/main/mslice/workspace/workspace.py) wrapper as logs in the underlying Mantid workspace so that they can be saved by `SaveNexus` and reloaded later.

**MSlice Version (please complete the following information):**
 - MSlice Version 2.4.0 (Mantid nightly 221013.2104)

**Comment by robertapplin** [comment]
I found that when you load a *.nxspe file, do a Scale operation, and then save it, it uses the `SaveNexus` algorithm. It should instead use the `SaveNXSPE` algorithm to make sure all metadata is saved appropriately. Doing this ensures that the scaled file can be reloaded into MSlice

We need to detect when a workspace is NXSPE, and use the `SaveNXSPE` algorithm when appropriate.
