### ISSUE TITLE
Lines missing on cut plot with reduced step sizes on pixel workspaces

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/mslice#842]
**Describe the bug**
When plotting a cut from a pixel workspace, when the cut is taken using a step smaller than that of the pixel workspace a number of the lines are missing. The amount of missing lines increases proportional to the difference between the step sizes.

Perhaps we should prevent cuts and slices from being taken that have a higher resolution than the parent dataset - I don't see any reason why you would want to do this?

I think this is possibly related to #728. When you take a slice from a pixel workspace with a higher resolution than that workspace, you get the following:
![image](https://user-images.githubusercontent.com/95620982/199952869-516b328d-0b95-4c7f-ab68-f227dd4ba1c2.png)

The gaps (N/As) in the data are likely the direct cause of the missing lines - prehaps the missing lines in #728 are also caused by this.

**To Reproduce**
Run the following script, after adjusting the file path to the `HYS_63373_4pixel` dataset.

# Python Script Generated by Mslice on 2022-11-04 10:06:01
```
import mslice.cli as mc
import mslice.plotting.pyplot as plt

HYS_63373_4pixel = mc.Load(Filename='C:/Users/mlc47243/Documents/mantid-data/HYS_63373_4pixel.nxspe', OutputWorkspace='HYS_63373_4pixel')
ws_HYS_63373_4pixel_QE = mc.MakeProjection(InputWorkspace=HYS_63373_4pixel, Axis1='|Q|', Axis2='DeltaE')

fig = plt.gcf()
fig.clf()
ax = fig.add_subplot(111, projection="mslice")
cut_ws_0 = mc.Cut(ws_HYS_63373_4pixel_QE, CutAxis="DeltaE,-0.5,0.5,0.05", IntegrationAxis="|Q|,0.2,0.3,0.0", NormToOne=False, IntensityCorrection=False, SampleTemperature=None)
ax.errorbar(cut_ws_0, label="HYS_63373_4pixel_QE 0.20<|Q|<0.30", color="#1f77b4", marker="o", ls="-", lw=1.5)

cut_ws_1 = mc.Cut(ws_HYS_63373_4pixel_QE, CutAxis="DeltaE,-0.5,0.5,0.035", IntegrationAxis="|Q|,0.2,0.3,0.0", NormToOne=False, IntensityCorrection=False, SampleTemperature=None)
ax.errorbar(cut_ws_1, label="HYS_63373_4pixel_QE 0.20<|Q|<0.30", color="#ff7f0e", marker="o", ls="-", lw=1.5)

cut_ws_2 = mc.Cut(ws_HYS_63373_4pixel_QE, CutAxis="DeltaE,-0.5,0.5,0.02", IntegrationAxis="|Q|,0.2,0.3,0.0", NormToOne=False, IntensityCorrection=False, SampleTemperature=None)
ax.errorbar(cut_ws_2, label="HYS_63373_4pixel_QE 0.20<|Q|<0.30", color="#2ca02c", marker="o", ls="-", lw=1.5)

from mslice.cli.helperfunctions import hide_a_line_and_errorbars, append_visible_handle_and_label
from mslice.util.compat import legend_set_draggable

# hide lines, errorbars, and legends
handles, labels = ax.get_legend_handles_labels()
visible_handles = []
visible_labels = []

append_visible_handle_and_label(visible_handles, handles, visible_labels, labels, 0)

append_visible_handle_and_label(visible_handles, handles, visible_labels, labels, 1)

append_visible_handle_and_label(visible_handles, handles, visible_labels, labels, 2)

legend_set_draggable(ax.legend(visible_handles, visible_labels, fontsize='medium'), True)

ax.set_title('')
ax.set_ylabel(r'Signal/#Events')
ax.set_xlabel(r'Energy Transfer (meV)')
ax.set_ylim(bottom=-0.0010965015655078642, top=0.14673213392107215)
ax.set_xlim(left=-0.5310344827586206, right=0.5310344827586206)
mc.Show()
```

**Expected behavior**
No missing lines.

**Comment by SilkeSchomann** [comment]
Instead of preventing cuts and slices with a higher resolution as the original dataset we could display a warning so that the user is aware that there is a valid reason for the missing lines.

**Comment by robertapplin** [comment]
After running the script, I get this:

![image](https://user-images.githubusercontent.com/40830825/226327197-30da0a00-8b9c-4f98-b47c-bfbbcfca9a86.png)


Is this the expected output?
