### ISSUE TITLE
Generated script file ignores grid

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mslice#855]
**Describe the bug**
Grid lines are not reproduced in generated script file (it works fine when the script is generated to clipboard though).

**To Reproduce**

1. On Linux load MAR21335_Ei60meV dataset 
2. Display slice
3. Enable grid
4. Save generated script to file
5. Open and run script file

**Comment by MialLewis** [comment]
I can't replicate this on `WSL` or `IDaaS`?

**Comment by SilkeSchomann** [comment]
Did you generate the script to file and not to clipboard?

**Comment by MialLewis** [comment]
Yes I did both and then compared the output

**Comment by SilkeSchomann** [comment]
I've just tried to reproduce this and could not :-)
