### ISSUE TITLE
Investigate replacement of nosetests by pytest

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mslice#858]
Nose has not been updated for several years now and is widely seen as outdated. Pytest is actively maintained, has a large user community and is supposed to be easier to use than unittest. 

It would be good to know if the advantages of switching to pytest outweigh the effort of porting our tests from nose to pytest.

**Comment by robertapplin** [comment]
I conda installed pytest and ran the following
```
PYTHONPATH=$PWD/src/ pytest tests/
```

It seemed to run quite well with some nice output to the cmd prompt. All tests pass, just a large number of warnings:

![image](https://user-images.githubusercontent.com/40830825/226586152-f0901679-d959-4a34-81f2-812834cd3a97.png)
