### ISSUE TITLE
Trying to save a cut that has been converted to GDOS leads to Mantid crashing

### ISSUE THREAD

**Issue by MohamedAlmaki** [mantidproject/mslice#955]
**Original reporter**: Mohamed Aouane

**Describe the bug**
When attempting to save a cut that has been converted to GDOS, Mantid crashes.

**To Reproduce**
Using the following information:
Instrument: MARI
RBNumber: 2310178
Run Number: 29091

**Expected behavior**
It shouldn't crash

**MSlice Version (please complete the following information):**
 - Mantid Version: 6.8.20231017.1653

**Comment by SilkeSchomann** [comment]
I've tried to reproduce this issue with different data sets without success.
