### ISSUE TITLE
Automatically generated scripts overwrite currently open plot

### ISSUE THREAD

**Issue by GuiMacielPereira** [mantidproject/mslice#968]
**Current Behaviour**
The scripts that are automatically generated by the scripting functionality overwrite an already open mslice plot.

**To Reproduce**
- Open a slice plot
- Click File > Generate Script to Clipboard
- Open a mantid editor tab and paste the script
- Go back to the currently open slice plot and change some characteristics, eg. zoom in
- Run the generated script in the mantid editor
- The plot produced by the script overwrites any existing changes

**Expected Behaviour**
In my perspective it makes more sense to create a new plot entirely, to prevent users from accidentally deleting the changes they had made.

**Comment by SilkeSchomann** [comment]
This behaviour can be prevented by clicking the `Keep` button on the original plot: https://mantidproject.github.io/mslice/quickstart.html#keep-make-current
