### ISSUE TITLE
Crash when saving MDHisto into mantid workbench

### ISSUE THREAD

**Issue by GuiMacielPereira** [mantidproject/mslice#972]
**Describe the bug**
Mantid crashes when saving workspace from MDHisto in mslice to Workspace in mantid. Reported by Mo ([mohamed.aouane@stfc.ac.uk](mailto:mohamed.aouane@stfc.ac.uk)).

**To Reproduce**
1. Load a workspace into MSlice
2. Do a cut 
3. Converted a cut into a GDOS on MSlice
4. Tried saving the GDOS cut from MDHisto to the Workbench
5. Mantid error

**Expected behavior**
No crash

**Screenshots**
If applicable/possible, add screenshots to help explain your problem.

**MSlice Version (please complete the following information):**
 - MSlice Version 2.6.0

**Comment by SilkeSchomann** [comment]
This problem does not occur with Mantid 6.7, but from 6.8 on.
