### ISSUE TITLE
Saving cuts with non-S(q,w) intensity option not working

### ISSUE THREAD

**Issue by mducle** [mantidproject/mslice#980]
Original reporter (to be notified): ISIS/Mo

**Describe the bug**

After plotting a 1D cut and selecting a different intensity option than the default (S(q,w)), if I save the cut, the saved data is the original intensity and not the one I selected.

**To Reproduce**

1. Open a file in MSlice (e.g. `MAR21335_Ei60meV.nxs` from the test suite)
2. Make a 1D cut (e.g. along `DeltaE` from `5` to `55` step `0.3` integrating along `|Q|` from `4` to `10`).
3. In the plot window, go to the `Intensity` menu and select `GDOS`. Put in `5` K as the temperature.
4. Then click the "Floppy disk" icon and select `Ascii` as the file format (bottom right).
5. Save to file - and plot the file with an external program (e.g. gnuplot or load it with `numpy.loadtxt` and plot it manually) - check that the lower energy peak (around 20meV) is more intense than the high energy peak - in the GDOS cut the two peaks are roughly the same height.

**Expected behavior**
The saved data file should reflect what is seen on the screen.

**Screenshots**
N/A

**MSlice Version (please complete the following information):**
 - MSlice Version `2.6.0` from Mantid `6.9.20240315.0914` (nightly). 

**Additional context**
When plotting the GDOS cut, an MDworkspace (not hidden) is created in the Mantid workspace window, which contains the correct (GDOS) data - after running `ConvertMDHistoToMatrixWorkspace` this can be saved with `SaveAscii` but this is a bit hard to use...

**Comment by SilkeSchomann** [comment]
This problem was fixed by https://github.com/mantidproject/mslice/pull/987 and is not present anymore in Mantid 6.10.
