### ISSUE TITLE
Crash when trying to save as .nxspe from plot window 

### ISSUE THREAD

**Issue by adriazalvarez** [mantidproject/mslice#984]
**Describe the bug**
Reported by: Ross Stewart
A crash was found by an user when trying to save a figure as .nxspe file from the `Save` toolbar button on the plot window.
As this is not possible, we should warn the user about this but is not necessary to raise the error report window ( similar to the behaviour in the mslice interface when trying to save .nxspe). 

**To Reproduce**
1. Go to MSlice
2. Open a test file: `MAR27691_red.nxs`
3. Click on display. Plot window should open. 
4. On the plot window, click on save , an select `.nxspe` as file extension. 
5. Error report window should be raised.
![image](https://github.com/mantidproject/mslice/assets/146007827/061a9bd4-3f85-4fbf-83a2-567807f735ce)

**Expected behavior**
User receives a warning, but no error report with the option to terminate is raised.

**Screenshots**
If applicable/possible, add screenshots to help explain your problem.

**MSlice Version (please complete the following information):**
 - MSlice Version 2.6.0

**Additional context**

**Comment by SilkeSchomann** [comment]
There is a similar crash when trying to save an `.nxspe` file as `.nxs`.
